<script>
  import * as Icon from '$lib';
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return '#' + n.slice(0, 6);
  };
</script>

<div class="flex flex-wrap p-4">
  <Icon.Accessibility16 size="40" color={random_hex_color_code()} />
  <Icon.Alert16 size="40" color={random_hex_color_code()} />
  <Icon.Alert24 size="40" color={random_hex_color_code()} />
  <Icon.AlertFill12 size="40" color={random_hex_color_code()} />
  <Icon.Apps16 size="40" color={random_hex_color_code()} />
  <Icon.Archive16 size="40" color={random_hex_color_code()} />
  <Icon.Archive24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowBoth16 size="40" color={random_hex_color_code()} />
  <Icon.ArrowBoth24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowDown16 size="40" color={random_hex_color_code()} />
  <Icon.ArrowDown24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowDownLeft24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowDownRight24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowLeft16 size="40" color={random_hex_color_code()} />
  <Icon.ArrowLeft24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowRight16 size="40" color={random_hex_color_code()} />
  <Icon.ArrowRight24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowSwitch16 size="40" color={random_hex_color_code()} />
  <Icon.ArrowSwitch24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowUp16 size="40" color={random_hex_color_code()} />
  <Icon.ArrowUp24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowUpLeft24 size="40" color={random_hex_color_code()} />
  <Icon.ArrowUpRight24 size="40" color={random_hex_color_code()} />
  <Icon.Beaker16 size="40" color={random_hex_color_code()} />
  <Icon.Beaker24 size="40" color={random_hex_color_code()} />
  <Icon.Bell16 size="40" color={random_hex_color_code()} />
  <Icon.Bell24 size="40" color={random_hex_color_code()} />
  <Icon.BellFill16 size="40" color={random_hex_color_code()} />
  <Icon.BellFill24 size="40" color={random_hex_color_code()} />
  <Icon.BellSlash16 size="40" color={random_hex_color_code()} />
  <Icon.BellSlash24 size="40" color={random_hex_color_code()} />
  <Icon.Blocked16 size="40" color={random_hex_color_code()} />
  <Icon.Blocked24 size="40" color={random_hex_color_code()} />
  <Icon.Bold16 size="40" color={random_hex_color_code()} />
  <Icon.Bold24 size="40" color={random_hex_color_code()} />
  <Icon.Book16 size="40" color={random_hex_color_code()} />
  <Icon.Book24 size="40" color={random_hex_color_code()} />
  <Icon.Bookmark16 size="40" color={random_hex_color_code()} />
  <Icon.Bookmark24 size="40" color={random_hex_color_code()} />
  <Icon.BookmarkFill24 size="40" color={random_hex_color_code()} />
  <Icon.BookmarkSlash16 size="40" color={random_hex_color_code()} />
  <Icon.BookmarkSlash24 size="40" color={random_hex_color_code()} />
  <Icon.BookmarkSlashFill24 size="40" color={random_hex_color_code()} />
  <Icon.Briefcase16 size="40" color={random_hex_color_code()} />
  <Icon.Briefcase24 size="40" color={random_hex_color_code()} />
  <Icon.Broadcast16 size="40" color={random_hex_color_code()} />
  <Icon.Broadcast24 size="40" color={random_hex_color_code()} />
  <Icon.Browser16 size="40" color={random_hex_color_code()} />
  <Icon.Browser24 size="40" color={random_hex_color_code()} />
  <Icon.Bug16 size="40" color={random_hex_color_code()} />
  <Icon.Bug24 size="40" color={random_hex_color_code()} />
  <Icon.Calendar16 size="40" color={random_hex_color_code()} />
  <Icon.Calendar24 size="40" color={random_hex_color_code()} />
  <Icon.Check16 size="40" color={random_hex_color_code()} />
  <Icon.Check24 size="40" color={random_hex_color_code()} />
  <Icon.CheckCircle16 size="40" color={random_hex_color_code()} />
  <Icon.CheckCircle24 size="40" color={random_hex_color_code()} />
  <Icon.CheckCircleFill12 size="40" color={random_hex_color_code()} />
  <Icon.CheckCircleFill16 size="40" color={random_hex_color_code()} />
  <Icon.CheckCircleFill24 size="40" color={random_hex_color_code()} />
  <Icon.Checklist16 size="40" color={random_hex_color_code()} />
  <Icon.Checklist24 size="40" color={random_hex_color_code()} />
  <Icon.ChevronDown16 size="40" color={random_hex_color_code()} />
  <Icon.ChevronDown24 size="40" color={random_hex_color_code()} />
  <Icon.ChevronLeft16 size="40" color={random_hex_color_code()} />
  <Icon.ChevronLeft24 size="40" color={random_hex_color_code()} />
  <Icon.ChevronRight16 size="40" color={random_hex_color_code()} />
  <Icon.ChevronRight24 size="40" color={random_hex_color_code()} />
  <Icon.ChevronUp16 size="40" color={random_hex_color_code()} />
  <Icon.ChevronUp24 size="40" color={random_hex_color_code()} />
  <Icon.Circle16 size="40" color={random_hex_color_code()} />
  <Icon.Circle24 size="40" color={random_hex_color_code()} />
  <Icon.CircleSlash16 size="40" color={random_hex_color_code()} />
  <Icon.CircleSlash24 size="40" color={random_hex_color_code()} />
  <Icon.Clock16 size="40" color={random_hex_color_code()} />
  <Icon.Clock24 size="40" color={random_hex_color_code()} />
  <Icon.Cloud16 size="40" color={random_hex_color_code()} />
  <Icon.Cloud24 size="40" color={random_hex_color_code()} />
  <Icon.CloudOffline16 size="40" color={random_hex_color_code()} />
  <Icon.CloudOffline24 size="40" color={random_hex_color_code()} />
  <Icon.Code16 size="40" color={random_hex_color_code()} />
  <Icon.Code24 size="40" color={random_hex_color_code()} />
  <Icon.CodeOfConduct16 size="40" color={random_hex_color_code()} />
  <Icon.CodeOfConduct24 size="40" color={random_hex_color_code()} />
  <Icon.CodeReview16 size="40" color={random_hex_color_code()} />
  <Icon.CodeReview24 size="40" color={random_hex_color_code()} />
  <Icon.CodeSquare16 size="40" color={random_hex_color_code()} />
  <Icon.CodeSquare24 size="40" color={random_hex_color_code()} />
  <Icon.Codescan16 size="40" color={random_hex_color_code()} />
  <Icon.Codescan24 size="40" color={random_hex_color_code()} />
  <Icon.CodescanCheckmark16 size="40" color={random_hex_color_code()} />
  <Icon.CodescanCheckmark24 size="40" color={random_hex_color_code()} />
  <Icon.Codespaces16 size="40" color={random_hex_color_code()} />
  <Icon.Codespaces24 size="40" color={random_hex_color_code()} />
  <Icon.Columns16 size="40" color={random_hex_color_code()} />
  <Icon.Columns24 size="40" color={random_hex_color_code()} />
  <Icon.Comment16 size="40" color={random_hex_color_code()} />
  <Icon.Comment24 size="40" color={random_hex_color_code()} />
  <Icon.CommentDiscussion16 size="40" color={random_hex_color_code()} />
  <Icon.CommentDiscussion24 size="40" color={random_hex_color_code()} />
  <Icon.Commit24 size="40" color={random_hex_color_code()} />
  <Icon.Container16 size="40" color={random_hex_color_code()} />
  <Icon.Container24 size="40" color={random_hex_color_code()} />
  <Icon.Copilot16 size="40" color={random_hex_color_code()} />
  <Icon.Copilot24 size="40" color={random_hex_color_code()} />
  <Icon.Copilot48 size="40" color={random_hex_color_code()} />
  <Icon.Copilot96 size="40" color={random_hex_color_code()} />
  <Icon.CopilotError16 size="40" color={random_hex_color_code()} />
  <Icon.CopilotWarning16 size="40" color={random_hex_color_code()} />
  <Icon.Copy16 size="40" color={random_hex_color_code()} />
  <Icon.Copy24 size="40" color={random_hex_color_code()} />
  <Icon.Cpu16 size="40" color={random_hex_color_code()} />
  <Icon.Cpu24 size="40" color={random_hex_color_code()} />
  <Icon.CreditCard16 size="40" color={random_hex_color_code()} />
  <Icon.CreditCard24 size="40" color={random_hex_color_code()} />
  <Icon.CrossReference16 size="40" color={random_hex_color_code()} />
  <Icon.CrossReference24 size="40" color={random_hex_color_code()} />
  <Icon.Dash16 size="40" color={random_hex_color_code()} />
  <Icon.Dash24 size="40" color={random_hex_color_code()} />
  <Icon.Database16 size="40" color={random_hex_color_code()} />
  <Icon.Database24 size="40" color={random_hex_color_code()} />
  <Icon.Dependabot16 size="40" color={random_hex_color_code()} />
  <Icon.Dependabot24 size="40" color={random_hex_color_code()} />
  <Icon.DesktopDownload16 size="40" color={random_hex_color_code()} />
  <Icon.DesktopDownload24 size="40" color={random_hex_color_code()} />
  <Icon.DeviceCamera16 size="40" color={random_hex_color_code()} />
  <Icon.DeviceCameraVideo16 size="40" color={random_hex_color_code()} />
  <Icon.DeviceCameraVideo24 size="40" color={random_hex_color_code()} />
  <Icon.DeviceDesktop16 size="40" color={random_hex_color_code()} />
  <Icon.DeviceDesktop24 size="40" color={random_hex_color_code()} />
  <Icon.DeviceMobile16 size="40" color={random_hex_color_code()} />
  <Icon.DeviceMobile24 size="40" color={random_hex_color_code()} />
  <Icon.Diamond16 size="40" color={random_hex_color_code()} />
  <Icon.Diamond24 size="40" color={random_hex_color_code()} />
  <Icon.Diff16 size="40" color={random_hex_color_code()} />
  <Icon.Diff24 size="40" color={random_hex_color_code()} />
  <Icon.DiffAdded16 size="40" color={random_hex_color_code()} />
  <Icon.DiffIgnored16 size="40" color={random_hex_color_code()} />
  <Icon.DiffModified16 size="40" color={random_hex_color_code()} />
  <Icon.DiffRemoved16 size="40" color={random_hex_color_code()} />
  <Icon.DiffRenamed16 size="40" color={random_hex_color_code()} />
  <Icon.Dot16 size="40" color={random_hex_color_code()} />
  <Icon.Dot24 size="40" color={random_hex_color_code()} />
  <Icon.DotFill16 size="40" color={random_hex_color_code()} />
  <Icon.DotFill24 size="40" color={random_hex_color_code()} />
  <Icon.Download16 size="40" color={random_hex_color_code()} />
  <Icon.Download24 size="40" color={random_hex_color_code()} />
  <Icon.Duplicate16 size="40" color={random_hex_color_code()} />
  <Icon.Duplicate24 size="40" color={random_hex_color_code()} />
  <Icon.Ellipsis16 size="40" color={random_hex_color_code()} />
  <Icon.Eye16 size="40" color={random_hex_color_code()} />
  <Icon.Eye24 size="40" color={random_hex_color_code()} />
  <Icon.EyeClosed16 size="40" color={random_hex_color_code()} />
  <Icon.EyeClosed24 size="40" color={random_hex_color_code()} />
  <Icon.FeedDiscussion16 size="40" color={random_hex_color_code()} />
  <Icon.FeedForked16 size="40" color={random_hex_color_code()} />
  <Icon.FeedHeart16 size="40" color={random_hex_color_code()} />
  <Icon.FeedMerged16 size="40" color={random_hex_color_code()} />
  <Icon.FeedPerson16 size="40" color={random_hex_color_code()} />
  <Icon.FeedRepo16 size="40" color={random_hex_color_code()} />
  <Icon.FeedRocket16 size="40" color={random_hex_color_code()} />
  <Icon.FeedStar16 size="40" color={random_hex_color_code()} />
  <Icon.FeedTag16 size="40" color={random_hex_color_code()} />
  <Icon.FeedTrophy16 size="40" color={random_hex_color_code()} />
  <Icon.File16 size="40" color={random_hex_color_code()} />
  <Icon.File24 size="40" color={random_hex_color_code()} />
  <Icon.FileAdded16 size="40" color={random_hex_color_code()} />
  <Icon.FileBadge16 size="40" color={random_hex_color_code()} />
  <Icon.FileBinary16 size="40" color={random_hex_color_code()} />
  <Icon.FileBinary24 size="40" color={random_hex_color_code()} />
  <Icon.FileCode16 size="40" color={random_hex_color_code()} />
  <Icon.FileCode24 size="40" color={random_hex_color_code()} />
  <Icon.FileDiff16 size="40" color={random_hex_color_code()} />
  <Icon.FileDiff24 size="40" color={random_hex_color_code()} />
  <Icon.FileDirectory16 size="40" color={random_hex_color_code()} />
  <Icon.FileDirectory24 size="40" color={random_hex_color_code()} />
  <Icon.FileDirectoryFill16 size="40" color={random_hex_color_code()} />
  <Icon.FileDirectoryFill24 size="40" color={random_hex_color_code()} />
  <Icon.FileDirectoryOpenFill16 size="40" color={random_hex_color_code()} />
  <Icon.FileMedia24 size="40" color={random_hex_color_code()} />
  <Icon.FileMoved16 size="40" color={random_hex_color_code()} />
  <Icon.FileRemoved16 size="40" color={random_hex_color_code()} />
  <Icon.FileSubmodule16 size="40" color={random_hex_color_code()} />
  <Icon.FileSubmodule24 size="40" color={random_hex_color_code()} />
  <Icon.FileSymlinkFile16 size="40" color={random_hex_color_code()} />
  <Icon.FileSymlinkFile24 size="40" color={random_hex_color_code()} />
  <Icon.FileZip16 size="40" color={random_hex_color_code()} />
  <Icon.FileZip24 size="40" color={random_hex_color_code()} />
  <Icon.Filter16 size="40" color={random_hex_color_code()} />
  <Icon.Filter24 size="40" color={random_hex_color_code()} />
  <Icon.Flame16 size="40" color={random_hex_color_code()} />
  <Icon.Flame24 size="40" color={random_hex_color_code()} />
  <Icon.Fold16 size="40" color={random_hex_color_code()} />
  <Icon.Fold24 size="40" color={random_hex_color_code()} />
  <Icon.FoldDown16 size="40" color={random_hex_color_code()} />
  <Icon.FoldDown24 size="40" color={random_hex_color_code()} />
  <Icon.FoldUp16 size="40" color={random_hex_color_code()} />
  <Icon.FoldUp24 size="40" color={random_hex_color_code()} />
  <Icon.Gear16 size="40" color={random_hex_color_code()} />
  <Icon.Gear24 size="40" color={random_hex_color_code()} />
  <Icon.Gift16 size="40" color={random_hex_color_code()} />
  <Icon.Gift24 size="40" color={random_hex_color_code()} />
  <Icon.GitBranch16 size="40" color={random_hex_color_code()} />
  <Icon.GitBranch24 size="40" color={random_hex_color_code()} />
  <Icon.GitCommit16 size="40" color={random_hex_color_code()} />
  <Icon.GitCommit24 size="40" color={random_hex_color_code()} />
  <Icon.GitCompare16 size="40" color={random_hex_color_code()} />
  <Icon.GitCompare24 size="40" color={random_hex_color_code()} />
  <Icon.GitMerge16 size="40" color={random_hex_color_code()} />
  <Icon.GitMerge24 size="40" color={random_hex_color_code()} />
  <Icon.GitPullRequest16 size="40" color={random_hex_color_code()} />
  <Icon.GitPullRequest24 size="40" color={random_hex_color_code()} />
  <Icon.GitPullRequestClosed16 size="40" color={random_hex_color_code()} />
  <Icon.GitPullRequestClosed24 size="40" color={random_hex_color_code()} />
  <Icon.GitPullRequestDraft16 size="40" color={random_hex_color_code()} />
  <Icon.GitPullRequestDraft24 size="40" color={random_hex_color_code()} />
  <Icon.Globe16 size="40" color={random_hex_color_code()} />
  <Icon.Globe24 size="40" color={random_hex_color_code()} />
  <Icon.Grabber16 size="40" color={random_hex_color_code()} />
  <Icon.Grabber24 size="40" color={random_hex_color_code()} />
  <Icon.Graph16 size="40" color={random_hex_color_code()} />
  <Icon.Graph24 size="40" color={random_hex_color_code()} />
  <Icon.Hash16 size="40" color={random_hex_color_code()} />
  <Icon.Hash24 size="40" color={random_hex_color_code()} />
  <Icon.Heading16 size="40" color={random_hex_color_code()} />
  <Icon.Heading24 size="40" color={random_hex_color_code()} />
  <Icon.Heart16 size="40" color={random_hex_color_code()} />
  <Icon.Heart24 size="40" color={random_hex_color_code()} />
  <Icon.HeartFill16 size="40" color={random_hex_color_code()} />
  <Icon.HeartFill24 size="40" color={random_hex_color_code()} />
  <Icon.History16 size="40" color={random_hex_color_code()} />
  <Icon.History24 size="40" color={random_hex_color_code()} />
  <Icon.Home16 size="40" color={random_hex_color_code()} />
  <Icon.Home24 size="40" color={random_hex_color_code()} />
  <Icon.HomeFill24 size="40" color={random_hex_color_code()} />
  <Icon.HorizontalRule16 size="40" color={random_hex_color_code()} />
  <Icon.HorizontalRule24 size="40" color={random_hex_color_code()} />
  <Icon.Hourglass16 size="40" color={random_hex_color_code()} />
  <Icon.Hourglass24 size="40" color={random_hex_color_code()} />
  <Icon.Hubot16 size="40" color={random_hex_color_code()} />
  <Icon.Hubot24 size="40" color={random_hex_color_code()} />
  <Icon.IdBadge16 size="40" color={random_hex_color_code()} />
  <Icon.Image16 size="40" color={random_hex_color_code()} />
  <Icon.Image24 size="40" color={random_hex_color_code()} />
  <Icon.Inbox16 size="40" color={random_hex_color_code()} />
  <Icon.Inbox24 size="40" color={random_hex_color_code()} />
  <Icon.Infinity16 size="40" color={random_hex_color_code()} />
  <Icon.Infinity24 size="40" color={random_hex_color_code()} />
  <Icon.Info16 size="40" color={random_hex_color_code()} />
  <Icon.Info24 size="40" color={random_hex_color_code()} />
  <Icon.IssueClosed16 size="40" color={random_hex_color_code()} />
  <Icon.IssueClosed24 size="40" color={random_hex_color_code()} />
  <Icon.IssueDraft16 size="40" color={random_hex_color_code()} />
  <Icon.IssueDraft24 size="40" color={random_hex_color_code()} />
  <Icon.IssueOpened16 size="40" color={random_hex_color_code()} />
  <Icon.IssueOpened24 size="40" color={random_hex_color_code()} />
  <Icon.IssueReopened16 size="40" color={random_hex_color_code()} />
  <Icon.IssueReopened24 size="40" color={random_hex_color_code()} />
  <Icon.Italic16 size="40" color={random_hex_color_code()} />
  <Icon.Italic24 size="40" color={random_hex_color_code()} />
  <Icon.Iterations16 size="40" color={random_hex_color_code()} />
  <Icon.Iterations24 size="40" color={random_hex_color_code()} />
  <Icon.KebabHorizontal16 size="40" color={random_hex_color_code()} />
  <Icon.KebabHorizontal24 size="40" color={random_hex_color_code()} />
  <Icon.Key16 size="40" color={random_hex_color_code()} />
  <Icon.Key24 size="40" color={random_hex_color_code()} />
  <Icon.KeyAsterisk16 size="40" color={random_hex_color_code()} />
  <Icon.Law16 size="40" color={random_hex_color_code()} />
  <Icon.Law24 size="40" color={random_hex_color_code()} />
  <Icon.LightBulb16 size="40" color={random_hex_color_code()} />
  <Icon.LightBulb24 size="40" color={random_hex_color_code()} />
  <Icon.Link16 size="40" color={random_hex_color_code()} />
  <Icon.Link24 size="40" color={random_hex_color_code()} />
  <Icon.LinkExternal16 size="40" color={random_hex_color_code()} />
  <Icon.LinkExternal24 size="40" color={random_hex_color_code()} />
  <Icon.ListOrdered16 size="40" color={random_hex_color_code()} />
  <Icon.ListOrdered24 size="40" color={random_hex_color_code()} />
  <Icon.ListUnordered16 size="40" color={random_hex_color_code()} />
  <Icon.ListUnordered24 size="40" color={random_hex_color_code()} />
  <Icon.Location16 size="40" color={random_hex_color_code()} />
  <Icon.Location24 size="40" color={random_hex_color_code()} />
  <Icon.Lock16 size="40" color={random_hex_color_code()} />
  <Icon.Lock24 size="40" color={random_hex_color_code()} />
  <Icon.Log16 size="40" color={random_hex_color_code()} />
  <Icon.LogoGist16 size="40" color={random_hex_color_code()} />
  <Icon.LogoGithub16 size="40" color={random_hex_color_code()} />
  <Icon.Mail16 size="40" color={random_hex_color_code()} />
  <Icon.Mail24 size="40" color={random_hex_color_code()} />
  <Icon.MarkGithub16 size="40" color={random_hex_color_code()} />
  <Icon.Markdown16 size="40" color={random_hex_color_code()} />
  <Icon.Megaphone16 size="40" color={random_hex_color_code()} />
  <Icon.Megaphone24 size="40" color={random_hex_color_code()} />
  <Icon.Mention16 size="40" color={random_hex_color_code()} />
  <Icon.Mention24 size="40" color={random_hex_color_code()} />
  <Icon.Meter16 size="40" color={random_hex_color_code()} />
  <Icon.Milestone16 size="40" color={random_hex_color_code()} />
  <Icon.Milestone24 size="40" color={random_hex_color_code()} />
  <Icon.Mirror16 size="40" color={random_hex_color_code()} />
  <Icon.Mirror24 size="40" color={random_hex_color_code()} />
  <Icon.Moon16 size="40" color={random_hex_color_code()} />
  <Icon.Moon24 size="40" color={random_hex_color_code()} />
  <Icon.MortarBoard16 size="40" color={random_hex_color_code()} />
  <Icon.MortarBoard24 size="40" color={random_hex_color_code()} />
  <Icon.MultiSelect16 size="40" color={random_hex_color_code()} />
  <Icon.MultiSelect24 size="40" color={random_hex_color_code()} />
  <Icon.Mute16 size="40" color={random_hex_color_code()} />
  <Icon.Mute24 size="40" color={random_hex_color_code()} />
  <Icon.NoEntry16 size="40" color={random_hex_color_code()} />
  <Icon.NoEntry24 size="40" color={random_hex_color_code()} />
  <Icon.NoEntryFill12 size="40" color={random_hex_color_code()} />
  <Icon.NorthStar16 size="40" color={random_hex_color_code()} />
  <Icon.NorthStar24 size="40" color={random_hex_color_code()} />
  <Icon.Note16 size="40" color={random_hex_color_code()} />
  <Icon.Note24 size="40" color={random_hex_color_code()} />
  <Icon.Number16 size="40" color={random_hex_color_code()} />
  <Icon.Number24 size="40" color={random_hex_color_code()} />
  <Icon.Organization16 size="40" color={random_hex_color_code()} />
  <Icon.Organization24 size="40" color={random_hex_color_code()} />
  <Icon.Package16 size="40" color={random_hex_color_code()} />
  <Icon.Package24 size="40" color={random_hex_color_code()} />
  <Icon.PackageDependencies16 size="40" color={random_hex_color_code()} />
  <Icon.PackageDependencies24 size="40" color={random_hex_color_code()} />
  <Icon.PackageDependents16 size="40" color={random_hex_color_code()} />
  <Icon.PackageDependents24 size="40" color={random_hex_color_code()} />
  <Icon.Paintbrush16 size="40" color={random_hex_color_code()} />
  <Icon.PaperAirplane16 size="40" color={random_hex_color_code()} />
  <Icon.PaperAirplane24 size="40" color={random_hex_color_code()} />
  <Icon.Paste16 size="40" color={random_hex_color_code()} />
  <Icon.Paste24 size="40" color={random_hex_color_code()} />
  <Icon.Pencil16 size="40" color={random_hex_color_code()} />
  <Icon.Pencil24 size="40" color={random_hex_color_code()} />
  <Icon.People16 size="40" color={random_hex_color_code()} />
  <Icon.People24 size="40" color={random_hex_color_code()} />
  <Icon.Person16 size="40" color={random_hex_color_code()} />
  <Icon.Person24 size="40" color={random_hex_color_code()} />
  <Icon.PersonAdd16 size="40" color={random_hex_color_code()} />
  <Icon.PersonAdd24 size="40" color={random_hex_color_code()} />
  <Icon.PersonFill16 size="40" color={random_hex_color_code()} />
  <Icon.PersonFill24 size="40" color={random_hex_color_code()} />
  <Icon.Pin16 size="40" color={random_hex_color_code()} />
  <Icon.Pin24 size="40" color={random_hex_color_code()} />
  <Icon.Play16 size="40" color={random_hex_color_code()} />
  <Icon.Play24 size="40" color={random_hex_color_code()} />
  <Icon.Plug16 size="40" color={random_hex_color_code()} />
  <Icon.Plug24 size="40" color={random_hex_color_code()} />
  <Icon.Plus16 size="40" color={random_hex_color_code()} />
  <Icon.Plus24 size="40" color={random_hex_color_code()} />
  <Icon.PlusCircle16 size="40" color={random_hex_color_code()} />
  <Icon.PlusCircle24 size="40" color={random_hex_color_code()} />
  <Icon.Project16 size="40" color={random_hex_color_code()} />
  <Icon.Project24 size="40" color={random_hex_color_code()} />
  <Icon.Pulse16 size="40" color={random_hex_color_code()} />
  <Icon.Pulse24 size="40" color={random_hex_color_code()} />
  <Icon.Question16 size="40" color={random_hex_color_code()} />
  <Icon.Question24 size="40" color={random_hex_color_code()} />
  <Icon.Quote16 size="40" color={random_hex_color_code()} />
  <Icon.Quote24 size="40" color={random_hex_color_code()} />
  <Icon.Reply16 size="40" color={random_hex_color_code()} />
  <Icon.Reply24 size="40" color={random_hex_color_code()} />
  <Icon.Repo16 size="40" color={random_hex_color_code()} />
  <Icon.Repo24 size="40" color={random_hex_color_code()} />
  <Icon.RepoClone16 size="40" color={random_hex_color_code()} />
  <Icon.RepoDeleted16 size="40" color={random_hex_color_code()} />
  <Icon.RepoForked16 size="40" color={random_hex_color_code()} />
  <Icon.RepoForked24 size="40" color={random_hex_color_code()} />
  <Icon.RepoLocked16 size="40" color={random_hex_color_code()} />
  <Icon.RepoLocked24 size="40" color={random_hex_color_code()} />
  <Icon.RepoPull16 size="40" color={random_hex_color_code()} />
  <Icon.RepoPush16 size="40" color={random_hex_color_code()} />
  <Icon.RepoPush24 size="40" color={random_hex_color_code()} />
  <Icon.RepoTemplate16 size="40" color={random_hex_color_code()} />
  <Icon.RepoTemplate24 size="40" color={random_hex_color_code()} />
  <Icon.Report16 size="40" color={random_hex_color_code()} />
  <Icon.Report24 size="40" color={random_hex_color_code()} />
  <Icon.Rocket16 size="40" color={random_hex_color_code()} />
  <Icon.Rocket24 size="40" color={random_hex_color_code()} />
  <Icon.Rows16 size="40" color={random_hex_color_code()} />
  <Icon.Rows24 size="40" color={random_hex_color_code()} />
  <Icon.Rss16 size="40" color={random_hex_color_code()} />
  <Icon.Rss24 size="40" color={random_hex_color_code()} />
  <Icon.Ruby16 size="40" color={random_hex_color_code()} />
  <Icon.Ruby24 size="40" color={random_hex_color_code()} />
  <Icon.ScreenFull16 size="40" color={random_hex_color_code()} />
  <Icon.ScreenFull24 size="40" color={random_hex_color_code()} />
  <Icon.ScreenNormal16 size="40" color={random_hex_color_code()} />
  <Icon.ScreenNormal24 size="40" color={random_hex_color_code()} />
  <Icon.Search16 size="40" color={random_hex_color_code()} />
  <Icon.Search24 size="40" color={random_hex_color_code()} />
  <Icon.Server16 size="40" color={random_hex_color_code()} />
  <Icon.Server24 size="40" color={random_hex_color_code()} />
  <Icon.Share16 size="40" color={random_hex_color_code()} />
  <Icon.Share24 size="40" color={random_hex_color_code()} />
  <Icon.ShareAndroid16 size="40" color={random_hex_color_code()} />
  <Icon.ShareAndroid24 size="40" color={random_hex_color_code()} />
  <Icon.Shield16 size="40" color={random_hex_color_code()} />
  <Icon.Shield24 size="40" color={random_hex_color_code()} />
  <Icon.ShieldCheck16 size="40" color={random_hex_color_code()} />
  <Icon.ShieldCheck24 size="40" color={random_hex_color_code()} />
  <Icon.ShieldLock16 size="40" color={random_hex_color_code()} />
  <Icon.ShieldLock24 size="40" color={random_hex_color_code()} />
  <Icon.ShieldX16 size="40" color={random_hex_color_code()} />
  <Icon.ShieldX24 size="40" color={random_hex_color_code()} />
  <Icon.SidebarCollapse16 size="40" color={random_hex_color_code()} />
  <Icon.SidebarCollapse24 size="40" color={random_hex_color_code()} />
  <Icon.SidebarExpand16 size="40" color={random_hex_color_code()} />
  <Icon.SidebarExpand24 size="40" color={random_hex_color_code()} />
  <Icon.SignIn16 size="40" color={random_hex_color_code()} />
  <Icon.SignIn24 size="40" color={random_hex_color_code()} />
  <Icon.SignOut16 size="40" color={random_hex_color_code()} />
  <Icon.SignOut24 size="40" color={random_hex_color_code()} />
  <Icon.SingleSelect16 size="40" color={random_hex_color_code()} />
  <Icon.SingleSelect24 size="40" color={random_hex_color_code()} />
  <Icon.Skip16 size="40" color={random_hex_color_code()} />
  <Icon.Skip24 size="40" color={random_hex_color_code()} />
  <Icon.Sliders16 size="40" color={random_hex_color_code()} />
  <Icon.Smiley16 size="40" color={random_hex_color_code()} />
  <Icon.Smiley24 size="40" color={random_hex_color_code()} />
  <Icon.SortAsc16 size="40" color={random_hex_color_code()} />
  <Icon.SortAsc24 size="40" color={random_hex_color_code()} />
  <Icon.SortDesc16 size="40" color={random_hex_color_code()} />
  <Icon.SortDesc24 size="40" color={random_hex_color_code()} />
  <Icon.Square16 size="40" color={random_hex_color_code()} />
  <Icon.Square24 size="40" color={random_hex_color_code()} />
  <Icon.SquareFill16 size="40" color={random_hex_color_code()} />
  <Icon.SquareFill24 size="40" color={random_hex_color_code()} />
  <Icon.Squirrel16 size="40" color={random_hex_color_code()} />
  <Icon.Squirrel24 size="40" color={random_hex_color_code()} />
  <Icon.Stack16 size="40" color={random_hex_color_code()} />
  <Icon.Stack24 size="40" color={random_hex_color_code()} />
  <Icon.Star16 size="40" color={random_hex_color_code()} />
  <Icon.Star24 size="40" color={random_hex_color_code()} />
  <Icon.StarFill16 size="40" color={random_hex_color_code()} />
  <Icon.StarFill24 size="40" color={random_hex_color_code()} />
  <Icon.Stop16 size="40" color={random_hex_color_code()} />
  <Icon.Stop24 size="40" color={random_hex_color_code()} />
  <Icon.Stopwatch16 size="40" color={random_hex_color_code()} />
  <Icon.Stopwatch24 size="40" color={random_hex_color_code()} />
  <Icon.Strikethrough16 size="40" color={random_hex_color_code()} />
  <Icon.Strikethrough24 size="40" color={random_hex_color_code()} />
  <Icon.Sun16 size="40" color={random_hex_color_code()} />
  <Icon.Sun24 size="40" color={random_hex_color_code()} />
  <Icon.Sync16 size="40" color={random_hex_color_code()} />
  <Icon.Sync24 size="40" color={random_hex_color_code()} />
  <Icon.Tab24 size="40" color={random_hex_color_code()} />
  <Icon.TabExternal16 size="40" color={random_hex_color_code()} />
  <Icon.Table16 size="40" color={random_hex_color_code()} />
  <Icon.Table24 size="40" color={random_hex_color_code()} />
  <Icon.Tag16 size="40" color={random_hex_color_code()} />
  <Icon.Tag24 size="40" color={random_hex_color_code()} />
  <Icon.Tasklist16 size="40" color={random_hex_color_code()} />
  <Icon.Tasklist24 size="40" color={random_hex_color_code()} />
  <Icon.Telescope16 size="40" color={random_hex_color_code()} />
  <Icon.Telescope24 size="40" color={random_hex_color_code()} />
  <Icon.TelescopeFill16 size="40" color={random_hex_color_code()} />
  <Icon.TelescopeFill24 size="40" color={random_hex_color_code()} />
  <Icon.Terminal16 size="40" color={random_hex_color_code()} />
  <Icon.Terminal24 size="40" color={random_hex_color_code()} />
  <Icon.ThreeBars16 size="40" color={random_hex_color_code()} />
  <Icon.Thumbsdown16 size="40" color={random_hex_color_code()} />
  <Icon.Thumbsdown24 size="40" color={random_hex_color_code()} />
  <Icon.Thumbsup16 size="40" color={random_hex_color_code()} />
  <Icon.Thumbsup24 size="40" color={random_hex_color_code()} />
  <Icon.Tools16 size="40" color={random_hex_color_code()} />
  <Icon.Tools24 size="40" color={random_hex_color_code()} />
  <Icon.Trash16 size="40" color={random_hex_color_code()} />
  <Icon.Trash24 size="40" color={random_hex_color_code()} />
  <Icon.TriangleDown16 size="40" color={random_hex_color_code()} />
  <Icon.TriangleDown24 size="40" color={random_hex_color_code()} />
  <Icon.TriangleLeft16 size="40" color={random_hex_color_code()} />
  <Icon.TriangleLeft24 size="40" color={random_hex_color_code()} />
  <Icon.TriangleRight16 size="40" color={random_hex_color_code()} />
  <Icon.TriangleRight24 size="40" color={random_hex_color_code()} />
  <Icon.TriangleUp16 size="40" color={random_hex_color_code()} />
  <Icon.TriangleUp24 size="40" color={random_hex_color_code()} />
  <Icon.Trophy16 size="40" color={random_hex_color_code()} />
  <Icon.Trophy24 size="40" color={random_hex_color_code()} />
  <Icon.Typography16 size="40" color={random_hex_color_code()} />
  <Icon.Typography24 size="40" color={random_hex_color_code()} />
  <Icon.Unfold16 size="40" color={random_hex_color_code()} />
  <Icon.Unfold24 size="40" color={random_hex_color_code()} />
  <Icon.Unlock16 size="40" color={random_hex_color_code()} />
  <Icon.Unlock24 size="40" color={random_hex_color_code()} />
  <Icon.Unmute16 size="40" color={random_hex_color_code()} />
  <Icon.Unmute24 size="40" color={random_hex_color_code()} />
  <Icon.Unverified16 size="40" color={random_hex_color_code()} />
  <Icon.Unverified24 size="40" color={random_hex_color_code()} />
  <Icon.Upload16 size="40" color={random_hex_color_code()} />
  <Icon.Upload24 size="40" color={random_hex_color_code()} />
  <Icon.Verified16 size="40" color={random_hex_color_code()} />
  <Icon.Verified24 size="40" color={random_hex_color_code()} />
  <Icon.Versions16 size="40" color={random_hex_color_code()} />
  <Icon.Versions24 size="40" color={random_hex_color_code()} />
  <Icon.Video16 size="40" color={random_hex_color_code()} />
  <Icon.Video24 size="40" color={random_hex_color_code()} />
  <Icon.Webhook16 size="40" color={random_hex_color_code()} />
  <Icon.Workflow16 size="40" color={random_hex_color_code()} />
  <Icon.Workflow24 size="40" color={random_hex_color_code()} />
  <Icon.X16 size="40" color={random_hex_color_code()} />
  <Icon.X24 size="40" color={random_hex_color_code()} />
  <Icon.XCircle16 size="40" color={random_hex_color_code()} />
  <Icon.XCircle24 size="40" color={random_hex_color_code()} />
  <Icon.XCircleFill12 size="40" color={random_hex_color_code()} />
  <Icon.XCircleFill16 size="40" color={random_hex_color_code()} />
  <Icon.XCircleFill24 size="40" color={random_hex_color_code()} />
  <Icon.Zap16 size="40" color={random_hex_color_code()} />
  <Icon.Zap24 size="40" color={random_hex_color_code()} />
</div>
